package jp.kantan.voicememo;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.Bundle;import android.speech.RecognizerIntent;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
 private static final int SPEECH=44; private LinearLayout memoList,timeList; private TextView summary;
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);summary=findViewById(R.id.summary);memoList=findViewById(R.id.memoList);timeList=findViewById(R.id.timeList);findViewById(R.id.speak).setOnClickListener(v->speak());findViewById(R.id.addTime).setOnClickListener(v->pickTime(-1));if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},3);ReminderScheduler.scheduleAll(this);render();if(getIntent().getBooleanExtra("speak",false))speak();}
 private void speak(){Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"ja-JP");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_PROMPT,"メモを話してください");try{startActivityForResult(i,SPEECH);}catch(Exception e){Toast.makeText(this,"この端末では音声入力を利用できません",Toast.LENGTH_LONG).show();}}
 protected void onActivityResult(int r,int code,Intent d){super.onActivityResult(r,code,d);if(r==SPEECH&&code==RESULT_OK&&d!=null){ArrayList<String>x=d.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(x!=null&&!x.isEmpty()){MemoStore.add(this,x.get(0));render();Toast.makeText(this,"メモしました",Toast.LENGTH_SHORT).show();}}}
 private void render(){List<MemoStore.Memo> ms=MemoStore.memos(this);int pending=MemoStore.pendingCount(this);summary.setText("未完了 "+pending+"件\n次の予定: "+nextTime());memoList.removeAllViews();for(int i=0;i<ms.size();i++){MemoStore.Memo m=ms.get(i);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);CheckBox cb=new CheckBox(this);String day=m.day.equals(MemoStore.today())?"今日":m.day;cb.setText("["+day+"] "+m.text);cb.setTextSize(17);cb.setChecked(m.done);cb.setPadding(8,10,4,10);row.addView(cb,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1));Button del=new Button(this);del.setText("削除");row.addView(del,new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT,LinearLayout.LayoutParams.WRAP_CONTENT));int at=i;cb.setOnCheckedChangeListener((v,on)->{List<MemoStore.Memo> a=MemoStore.memos(this);if(at<a.size()){a.get(at).done=on;MemoStore.saveMemos(this,a);render();}});del.setOnClickListener(v->new AlertDialog.Builder(this).setMessage("このメモを削除しますか？").setPositiveButton("削除",(d,w)->{List<MemoStore.Memo>a=MemoStore.memos(this);if(at<a.size()){a.remove(at);MemoStore.saveMemos(this,a);render();}}).setNegativeButton("やめる",null).show());memoList.addView(row);}if(ms.isEmpty()){TextView e=new TextView(this);e.setText("まだメモはありません");e.setTextSize(17);e.setPadding(8,18,8,18);memoList.addView(e);}timeList.removeAllViews();List<String> ts=MemoStore.times(this);for(int i=0;i<ts.size();i++){Button b=new Button(this);b.setText(ts.get(i)+"　変更・削除");b.setTextSize(18);int at=i;b.setOnClickListener(v->timeMenu(at));timeList.addView(b);}}
 private String nextTime(){List<String>ts=MemoStore.times(this);Calendar n=Calendar.getInstance();int now=n.get(Calendar.HOUR_OF_DAY)*60+n.get(Calendar.MINUTE);for(String t:ts){String[]p=t.split(":");if(Integer.parseInt(p[0])*60+Integer.parseInt(p[1])>now)return "今日 "+t;}return ts.isEmpty()?"設定なし":"明日 "+ts.get(0);}
 private void timeMenu(int at){new AlertDialog.Builder(this).setTitle(MemoStore.times(this).get(at)).setItems(new String[]{"時刻を変更","この通知を削除"},(d,w)->{if(w==0)pickTime(at);else{List<String>a=MemoStore.times(this);a.remove(at);MemoStore.saveTimes(this,a);render();}}).show();}
 private void pickTime(int at){Calendar c=Calendar.getInstance();new TimePickerDialog(this,(v,h,m)->{String t=String.format(Locale.JAPAN,"%02d:%02d",h,m);List<String>a=MemoStore.times(this);if(at<0)a.add(t);else a.set(at,t);MemoStore.saveTimes(this,a);render();},c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE),true).show();}
}
